import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Path2D;
import java.awt.geom.PathIterator;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;

/**
 * Builds every platform's app icon from `icon/mdmoney-light.svg` and `icon/mdmoney-dark.svg`, the
 * single source of the artwork. Run from the repo root after changing either SVG:
 *
 *     java scripts/GenerateIcons.java
 *
 * It needs nothing but a JDK: the SVGs use only `rect`, `circle` and `path` made of M/L segments, and
 * that subset is read here directly (anything else fails loudly rather than being dropped).
 *
 * Outputs — all committed, so the app builds without running this:
 * - Android: an adaptive icon (vector foreground, colour background, monochrome for themed icons),
 *   light in `drawable`/`values`, dark in the `-night` variants.
 * - iOS: a 1024px `AppIcon` asset, with the dark SVG as its dark appearance.
 * - Desktop: `.ico` (Windows), `.icns` (macOS), `.png` (Linux) for packaging, and a Compose vector
 *   resource for the window icon.
 */
public class GenerateIcons {

    /** Android's adaptive-icon canvas, and the radius of the circle no launcher mask ever crops. */
    static final double ADAPTIVE_CANVAS = 108, ADAPTIVE_SAFE_RADIUS = 32;

    public static void main(String[] args) throws IOException {
        Path root = Path.of(args.length > 0 ? args[0] : ".");
        Icon light = Icon.parse(Files.readString(root.resolve("icon/mdmoney-light.svg")));
        Icon dark = Icon.parse(Files.readString(root.resolve("icon/mdmoney-dark.svg")));

        Path res = root.resolve("composeApp/src/androidMain/res");
        write(res.resolve("mipmap-anydpi-v26/ic_launcher.xml"), adaptiveIcon());
        write(res.resolve("mipmap-anydpi-v26/ic_launcher_round.xml"), adaptiveIcon());
        write(res.resolve("drawable/ic_launcher_foreground.xml"), light.adaptiveForeground());
        write(res.resolve("drawable-night/ic_launcher_foreground.xml"), dark.adaptiveForeground());
        write(res.resolve("values/ic_launcher_background.xml"), backgroundColor(light));
        write(res.resolve("values-night/ic_launcher_background.xml"), backgroundColor(dark));

        write(root.resolve("composeApp/src/commonMain/composeResources/drawable/app_icon.xml"),
            light.vectorDrawable());

        Path appIcon = root.resolve("iosApp/iosApp/Assets.xcassets/AppIcon.appiconset");
        Files.createDirectories(appIcon);
        Files.write(appIcon.resolve("AppIcon.png"), light.png(1024));
        Files.write(appIcon.resolve("AppIcon-Dark.png"), dark.png(1024));

        Path desktop = root.resolve("composeApp/icons");
        Files.createDirectories(desktop);
        Files.write(desktop.resolve("mdmoney.png"), light.png(512));
        Files.write(desktop.resolve("mdmoney.ico"), light.ico(16, 24, 32, 48, 64, 128, 256));
        Files.write(desktop.resolve("mdmoney.icns"), light.icns());

        System.out.println("Icons written.");
    }

    static void write(Path file, String text) throws IOException {
        Files.createDirectories(file.getParent());
        Files.writeString(file, text);
    }

    static final String GENERATED = "<!-- Generated by scripts/GenerateIcons.java from icon/*.svg — do not edit by hand. -->\n";

    static String adaptiveIcon() {
        return """
            <?xml version="1.0" encoding="utf-8"?>
            %s<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
                <background android:drawable="@color/ic_launcher_background" />
                <foreground android:drawable="@drawable/ic_launcher_foreground" />
                <monochrome android:drawable="@drawable/ic_launcher_foreground" />
            </adaptive-icon>
            """.formatted(GENERATED);
    }

    static String backgroundColor(Icon icon) {
        return """
            <?xml version="1.0" encoding="utf-8"?>
            %s<resources>
                <color name="ic_launcher_background">%s</color>
            </resources>
            """.formatted(GENERATED, icon.background().fill);
    }

    // ---------------------------------------------------------------------------------------------

    /** One drawn SVG element: its outline in viewBox units, and how it is painted. */
    record Element(String kind, Shape shape, String pathData, String fill, String stroke, double strokeWidth, String cap) {

        boolean isBackground(double size) {
            Rectangle2D b = shape.getBounds2D();
            return kind.equals("rect") && fill != null && b.getX() <= 0 && b.getY() <= 0
                && b.getWidth() >= size && b.getHeight() >= size;
        }

        /** The inset border: it frames the square icon and has no place inside a launcher's mask. */
        boolean isFrame() {
            return kind.equals("rect") && fill == null;
        }

        BasicStroke basicStroke(double scale) {
            int javaCap = switch (cap) {
                case "square" -> BasicStroke.CAP_SQUARE;
                case "round" -> BasicStroke.CAP_ROUND;
                default -> BasicStroke.CAP_BUTT;
            };
            return new BasicStroke((float) (strokeWidth * scale), javaCap, BasicStroke.JOIN_MITER);
        }

        /** The painted area, strokes included — what the adaptive icon must keep inside its safe zone. */
        Shape paintedArea() {
            return stroke != null ? basicStroke(1).createStrokedShape(shape) : shape;
        }

        String vectorPath(String indent) {
            StringBuilder out = new StringBuilder(indent).append("<path\n");
            out.append(indent).append("    android:pathData=\"").append(pathData).append("\"");
            if (fill != null) out.append("\n").append(indent).append("    android:fillColor=\"").append(fill).append("\"");
            if (stroke != null) {
                out.append("\n").append(indent).append("    android:strokeColor=\"").append(stroke).append("\"");
                out.append("\n").append(indent).append("    android:strokeWidth=\"").append(num(strokeWidth)).append("\"");
                out.append("\n").append(indent).append("    android:strokeLineCap=\"").append(cap).append("\"");
                out.append("\n").append(indent).append("    android:strokeLineJoin=\"miter\"");
            }
            return out.append(" />\n").toString();
        }
    }

    record Icon(double size, List<Element> elements) {

        static final Pattern ELEMENT = Pattern.compile("<(rect|circle|path)\\b([^>]*)/>");
        static final Pattern ATTRIBUTE = Pattern.compile("([\\w-]+)=\"([^\"]*)\"");

        static Icon parse(String svg) {
            Matcher viewBox = Pattern.compile("viewBox=\"0 0 ([\\d.]+) ([\\d.]+)\"").matcher(svg);
            if (!viewBox.find() || !viewBox.group(1).equals(viewBox.group(2))) {
                throw new IllegalArgumentException("icon SVG needs a square viewBox starting at 0 0");
            }
            double size = Double.parseDouble(viewBox.group(1));

            String body = svg.replaceAll("<title>.*?</title>", "").replaceAll("<\\?xml[^>]*>", "");
            Matcher unknown = Pattern.compile("<(?!/?svg\\b|rect\\b|circle\\b|path\\b)(\\w+)").matcher(body);
            if (unknown.find()) throw new IllegalArgumentException("unsupported SVG element <" + unknown.group(1) + ">");

            List<Element> elements = new ArrayList<>();
            Matcher m = ELEMENT.matcher(body);
            while (m.find()) {
                Map<String, String> a = new LinkedHashMap<>();
                Matcher attr = ATTRIBUTE.matcher(m.group(2));
                while (attr.find()) a.put(attr.group(1), attr.group(2));
                elements.add(element(m.group(1), a));
            }
            return new Icon(size, elements);
        }

        static Element element(String kind, Map<String, String> a) {
            for (String key : a.keySet()) {
                if (!List.of("x", "y", "width", "height", "cx", "cy", "r", "d", "fill", "stroke",
                    "stroke-width", "stroke-linecap").contains(key)) {
                    throw new IllegalArgumentException("unsupported attribute " + key + " on <" + kind + ">");
                }
            }
            String fill = color(a.getOrDefault("fill", "#000000"));
            String stroke = a.containsKey("stroke") ? color(a.get("stroke")) : null;
            double strokeWidth = Double.parseDouble(a.getOrDefault("stroke-width", "1"));
            String cap = a.getOrDefault("stroke-linecap", "butt");
            return switch (kind) {
                case "rect" -> {
                    double x = d(a, "x"), y = d(a, "y"), w = d(a, "width"), h = d(a, "height");
                    String data = "M" + num(x) + "," + num(y) + " H" + num(x + w) + " V" + num(y + h)
                        + " H" + num(x) + " Z";
                    yield new Element(kind, new Rectangle2D.Double(x, y, w, h), data, fill, stroke, strokeWidth, cap);
                }
                case "circle" -> {
                    double cx = d(a, "cx"), cy = d(a, "cy"), r = d(a, "r");
                    String data = "M" + num(cx - r) + "," + num(cy) + " A" + num(r) + "," + num(r) + " 0 1,0 "
                        + num(cx + r) + "," + num(cy) + " A" + num(r) + "," + num(r) + " 0 1,0 "
                        + num(cx - r) + "," + num(cy) + " Z";
                    Shape shape = new Ellipse2D.Double(cx - r, cy - r, 2 * r, 2 * r);
                    yield new Element(kind, shape, data, fill, stroke, strokeWidth, cap);
                }
                default -> {
                    String data = a.get("d").trim();
                    yield new Element(kind, path(data), data, fill, stroke, strokeWidth, cap);
                }
            };
        }

        static Path2D path(String d) {
            Path2D.Double path = new Path2D.Double();
            Matcher cmd = Pattern.compile("([MLml])\\s*([-\\d.]+)[\\s,]+([-\\d.]+)").matcher(d);
            String leftover = d.replaceAll("([MLml])\\s*([-\\d.]+)[\\s,]+([-\\d.]+)", "").trim();
            if (!leftover.isEmpty()) throw new IllegalArgumentException("unsupported path data: " + leftover);
            while (cmd.find()) {
                double x = Double.parseDouble(cmd.group(2)), y = Double.parseDouble(cmd.group(3));
                if (Character.isLowerCase(cmd.group(1).charAt(0))) {
                    x += path.getCurrentPoint().getX();
                    y += path.getCurrentPoint().getY();
                }
                if (cmd.group(1).equalsIgnoreCase("M")) path.moveTo(x, y); else path.lineTo(x, y);
            }
            return path;
        }

        static String color(String value) {
            if (value.equals("none")) return null;
            if (!value.matches("#[0-9A-Fa-f]{6}")) throw new IllegalArgumentException("colour must be #RRGGBB: " + value);
            return value.toUpperCase(Locale.ROOT);
        }

        static double d(Map<String, String> a, String key) {
            return Double.parseDouble(a.getOrDefault(key, "0"));
        }

        Element background() {
            return elements.stream().filter(e -> e.isBackground(size)).findFirst()
                .orElseThrow(() -> new IllegalArgumentException("icon SVG needs a full-size background <rect>"));
        }

        List<Element> artwork() {
            return elements.stream().filter(e -> !e.isBackground(size) && !e.isFrame()).toList();
        }

        /** The full square icon, background and frame included, as a vector drawable. */
        String vectorDrawable() {
            StringBuilder out = new StringBuilder("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n").append(GENERATED);
            out.append("<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n")
                .append("    android:width=\"").append(num(size)).append("dp\"\n")
                .append("    android:height=\"").append(num(size)).append("dp\"\n")
                .append("    android:viewportWidth=\"").append(num(size)).append("\"\n")
                .append("    android:viewportHeight=\"").append(num(size)).append("\">\n");
            elements.forEach(e -> out.append(e.vectorPath("    ")));
            return out.append("</vector>\n").toString();
        }

        /**
         * The artwork alone, centred on Android's 108dp canvas and scaled so its furthest painted
         * point sits inside the safe circle — launchers crop to circles, squircles and teardrops.
         */
        String adaptiveForeground() {
            List<double[]> points = new ArrayList<>();
            Rectangle2D bounds = null;
            for (Element e : artwork()) {
                Shape area = e.paintedArea();
                bounds = bounds == null ? area.getBounds2D() : bounds.createUnion(area.getBounds2D());
                PathIterator it = area.getPathIterator(null, 0.05);
                double[] c = new double[6];
                for (; !it.isDone(); it.next()) {
                    if (it.currentSegment(c) != PathIterator.SEG_CLOSE) points.add(new double[] {c[0], c[1]});
                }
            }
            double cx = bounds.getCenterX(), cy = bounds.getCenterY();
            double radius = points.stream().mapToDouble(p -> Math.hypot(p[0] - cx, p[1] - cy)).max().orElseThrow();
            double scale = ADAPTIVE_SAFE_RADIUS / radius;
            double center = ADAPTIVE_CANVAS / 2;

            StringBuilder out = new StringBuilder("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n").append(GENERATED);
            out.append("<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n")
                .append("    android:width=\"108dp\"\n    android:height=\"108dp\"\n")
                .append("    android:viewportWidth=\"108\"\n    android:viewportHeight=\"108\">\n")
                .append("    <group\n")
                .append("        android:scaleX=\"").append(num(scale)).append("\"\n")
                .append("        android:scaleY=\"").append(num(scale)).append("\"\n")
                .append("        android:translateX=\"").append(num(center - cx * scale)).append("\"\n")
                .append("        android:translateY=\"").append(num(center - cy * scale)).append("\">\n");
            artwork().forEach(e -> out.append(e.vectorPath("        ")));
            return out.append("    </group>\n</vector>\n").toString();
        }

        /** Opaque (no alpha channel) — the App Store rejects an icon with one. */
        BufferedImage render(int px) {
            BufferedImage image = new BufferedImage(px, px, BufferedImage.TYPE_INT_RGB);
            Graphics2D g = image.createGraphics();
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);
            g.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            double scale = px / size;
            AffineTransform toPixels = AffineTransform.getScaleInstance(scale, scale);
            for (Element e : elements) {
                Shape shape = toPixels.createTransformedShape(e.shape);
                if (e.fill != null) {
                    g.setColor(Color.decode(e.fill));
                    g.fill(shape);
                }
                if (e.stroke != null) {
                    g.setColor(Color.decode(e.stroke));
                    g.setStroke(e.basicStroke(scale));
                    g.draw(shape);
                }
            }
            g.dispose();
            return image;
        }

        byte[] png(int px) throws IOException {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            ImageIO.write(render(px), "png", out);
            return out.toByteArray();
        }

        /** A Windows icon holding one PNG per size (supported since Vista). */
        byte[] ico(int... sizes) throws IOException {
            List<byte[]> images = new ArrayList<>();
            for (int s : sizes) images.add(png(s));
            int offset = 6 + 16 * sizes.length;
            ByteBuffer header = ByteBuffer.allocate(offset).order(ByteOrder.LITTLE_ENDIAN);
            header.putShort((short) 0).putShort((short) 1).putShort((short) sizes.length);
            for (int i = 0; i < sizes.length; i++) {
                int s = sizes[i];
                header.put((byte) (s >= 256 ? 0 : s)).put((byte) (s >= 256 ? 0 : s))
                    .put((byte) 0).put((byte) 0).putShort((short) 1).putShort((short) 32)
                    .putInt(images.get(i).length).putInt(offset);
                offset += images.get(i).length;
            }
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            out.write(header.array());
            for (byte[] image : images) out.write(image);
            return out.toByteArray();
        }

        /** A macOS icon with the PNG-backed entries, 16px through 1024px (retina 512). */
        byte[] icns() throws IOException {
            Map<String, Integer> types = new LinkedHashMap<>();
            types.put("icp4", 16);
            types.put("icp5", 32);
            types.put("icp6", 64);
            types.put("ic07", 128);
            types.put("ic08", 256);
            types.put("ic09", 512);
            types.put("ic10", 1024);
            ByteArrayOutputStream body = new ByteArrayOutputStream();
            for (Map.Entry<String, Integer> t : types.entrySet()) {
                byte[] image = png(t.getValue());
                body.write(t.getKey().getBytes(java.nio.charset.StandardCharsets.US_ASCII));
                body.write(ByteBuffer.allocate(4).putInt(8 + image.length).array());
                body.write(image);
            }
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            out.write("icns".getBytes(java.nio.charset.StandardCharsets.US_ASCII));
            out.write(ByteBuffer.allocate(4).putInt(8 + body.size()).array());
            body.writeTo(out);
            return out.toByteArray();
        }
    }

    static String num(double v) {
        String s = String.format(Locale.ROOT, "%.4f", v).replaceAll("0+$", "");
        return s.endsWith(".") ? s.substring(0, s.length() - 1) : s;
    }
}
